apiVersion: v2
name: git-testing
description: A Helm chart for git-testing app

type: application
version: 0.1.0

appVersion: sha-3d91d02

dependencies:
  - name: helmet
    version: 0.14.0
    repository: https://charts.companyinfo.dev
    import-values: # <== It is mandatory if you want to import the Helmet default values.
      - defaults
