name: deploy

on:
  workflow_dispatch:
    inputs:
      proddeploy:
        description: "Deploy till production?"
        required: false
        type: boolean
        default: false

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig

      - name: Deploy to Kubernetes using Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          echo "Deploy to development"
          helm upgrade --install git-testing-devt k8s/chart/git-testing \
            --values k8s/chart/git-testing/k3d-devt-values.yaml \
            --namespace default \
            --hide-notes

          if [ "${{ inputs.proddeploy }}" == "true" ]; then
            echo "Deploy to production"
            helm upgrade --install git-testing-prod k8s/chart/git-testing \
              --values k8s/chart/git-testing/k3d-prod-values.yaml \
              --namespace default \
              --hide-notes
          fi
