name: deploy

on:
  workflow_dispatch:
    inputs:
      proddeploy:
        description: "Deploy till production"
        required: false
        type: boolean
        default: false

jobs:
  helm-deploy:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig

      - name: Deploy to Kubernetes using Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          echo "Deploy to development"
          dtag=`yq .image.tag k8s/helm-values/k3d-devt-values.yaml`
          helm upgrade --install git-testing-devt onechart \
            --repo https://chart.onechart.dev \
            --version 0.73.0 \
            --values k8s/helm-values/k3d-devt-values.yaml \
            --namespace default \
            --hide-notes \
            --description "Upgrade completed to tag: $dtag"

          if [ "${{ inputs.proddeploy }}" == "true" ]; then
            echo "Deploy to production"
            ptag=`yq .image.tag k8s/helm-values/k3d-prod-values.yaml`
            helm upgrade --install git-testing-prod onechart \
              --repo https://chart.onechart.dev \
              --version 0.73.0 \
              --values k8s/helm-values/k3d-prod-values.yaml \
              --namespace default \
              --hide-notes \
              --description "Upgrade completed to tag: $ptag"
          fi
