name: deploy

on:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Create kubeconfig file
        run: echo "${{ secrets.KUBE_CONFIG }}" > ${{ github.workspace }}/kubeconfig

      - name: Deploy to Kubernetes using Helm
        env:
          KUBECONFIG: ${{ github.workspace }}/kubeconfig
        run: |
          helm version
